/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-12-16 下午8:24' with Gradle 3.0
 *
 * @author Administrator, @date 16-12-16 下午8:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
